accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CleanLogoutView.as_view(), name='logout'),
    path('logout/confirm/', CustomLogoutView.as_view(), name='logout_confirm'),
    path('signup/', signup_view, name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update/profile/', ProfileUpdateView.as_view(), name='update_profile'),
    path('password/change/', ChangePasswordView.as_view(), name='password_change'),
    path('delete/account/', DeleteAccountView.as_view(), name='delete_account'),
    path('password/reset/', CustomPasswordReset.as_view(), name='password_reset'),
    path('password/reset/done/', CustomPasswordDone.as_view(), name='password_reset_done'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordConfirm.as_view(), name='password_reset_confirm'),
    path('password/reset/complete/', CustomPasswordComplete.as_view(), name='password_reset_complete'),

    
    
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'
urlpatterns = [
    path('add/', CartAddView.as_view(), name='cart_add'),
    path('remove/', CartRemoveView.as_view(), name='cart_remove'),
    path('delete/', CartDeleteView.as_view(), name='cart_delete'),
    path('', CartSummaryView.as_view(), name='cart'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about-us/', include('pages.urls', namespace='pages')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('product.urls', namespace='product')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import (
    ProductListView,
    ProductDetailView,
    CategoryProductListView,
    CommentUpdateView,
    CommentDeleteView,
    SearchView,
    FavouritesView,
    ProductFavouritesView
)

app_name = 'product'
urlpatterns = [
    path('favourite/<slug:slug>/', FavouritesView.as_view(), name='favourite_product'),
    path('favourites/list/', ProductFavouritesView.as_view(), name='favourite_list'), 
    path('search/', SearchView.as_view(), name='search'),
    path('<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('comment/<slug:slug>/edit/', CommentUpdateView.as_view(), name='comment_edit'),
    path('comment/<slug:slug>/delete/', CommentDeleteView.as_view(), name='comment_delete'),
    path('category/<slug:slug>/', CategoryProductListView.as_view(), name='category_product'),
    path('', ProductListView.as_view(), name='products'),
]

product/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User


class Category(models.Model):
    category = models.CharField(max_length=25)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def __str__(self):
        return self.category
    
        
class Product(models.Model):    
    name = models.CharField(max_length=50)
    description = models.TextField()
    info = models.CharField(max_length=250, default='info')
    price = models.DecimalField(default=0, decimal_places=2, max_digits=10)
    is_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(default=0, decimal_places=2, max_digits=10)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tumbnail = models.ImageField(upload_to='tumbnails/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    favourites = models.ManyToManyField(User, related_name='favourites', blank=True)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={"slug": self.slug})

        
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.CharField(max_length=150)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True, null=True)


    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("product:product_detail")

    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='covers/')
    
    def __str__(self):
        return self.product.name
    
class Color(models.Model):
    color = models.CharField(max_length=15)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,  blank=True, null=True, related_name='color')

    def __str__(self):
        return self.color
    
    

product/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)
        widgets = {
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Write Your Comment Here...'
            })
        }

product/views.py
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from .models import Product, Category, Comment, Color
from django.shortcuts import get_object_or_404, redirect
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from django.views import View
from django.shortcuts import render
from django.db.models import Q
from django.contrib import messages

class ProductListView(ListView):
    model = Product
    template_name = 'products/products.html'
    context_object_name = 'products'
    paginate_by = 1
    ordering = ['-created_at']  # Add ordering to fix pagination warning
        
class CategoryProductListView(ListView):
    model = Product  
    template_name = 'products/category_products.html'
    context_object_name = 'products'

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return Product.objects.filter(category=self.category, is_active=True).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context

class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        context['newarrivals'] = Product.objects.filter(is_active=True).order_by('-created_at')[:4]
        context['comments'] = Comment.objects.filter(product=self.object).order_by('-created_at')
        context['form'] = CommentForm()
        context['colors'] = Color.objects.filter(product=product)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = CommentForm(request.POST)
        if form.is_valid() and request.user.is_authenticated:
            comment = form.save(commit=False)
            comment.product = self.object
            comment.author = request.user
            comment.save()
        return self.get(request, *args, **kwargs)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'products/comment_form.html'

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('product:product_detail', kwargs={'slug': self.object.product.slug})

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'products/comment_confirm_delete.html'

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('product:product_detail', kwargs={'slug': self.object.product.slug})

class SearchView(View):
    template_name = 'products/search.html'

    def post(self, request, *args, **kwargs):
        searched = request.POST.get('searched')
        searched = Product.objects.filter(Q(name__icontains=searched)|Q(description__icontains=searched))

        if not searched:
            messages.error(request, 'No Results Found')
            return render(request, self.template_name, {})

        else:
            context = {'searched':searched}
            return render(request, self.template_name, context)
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})
    
class FavouritesView(LoginRequiredMixin, View):
    def post(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        
        if product.favourites.filter(id=request.user.id).exists():
            product.favourites.remove(request.user)
            messages.success(request, 'Remove From Favorites')
        else:
            product.favourites.add(request.user)
            messages.success(request, 'Add To Favorites')
            
        return redirect(reverse('product:product_detail', kwargs={'slug': slug})) 

class ProductFavouritesView(LoginRequiredMixin, View):
    def get(self, request):
        favourites = request.user.favourites.all()
        context = {'favourites': favourites}
        return render(request, 'products/favouritelist.html', context)  

    
    
    

product/templates/products/category_products.html
{% extends "base/base.html" %}
{% load humanize %}

{% block title %}{{category.category}}{% endblock title %}

{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">{{category.category}}</h1>
            <p class="lead fw-normal text-white-50 mb-0">Best Products Are Here!</p>
        </div>
    </div>
</header>
{% endblock header %}


{% block main %}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        {% if product.is_sale %}
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                        {% endif %}
                        <img class="card-img-top" src="{{ product.tumbnail.url }}" alt="{{product.name}}" />
                        <div class="card-body p-4">
                            <div class="text-center">
                                <h5 class="fw-bolder">{{product.name}}</h5>
                                {% if product.is_sale %}
                                <span class="text-muted text-decoration-line-through">${{product.price|intcomma}}</span>
                                ${{product.sale_price}}
                                {% else %}
                                ${{product.price|intcomma}}
                                {% endif %}
                                <br>
                                {{product.category}}
                            </div>
                        </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product:product_detail' product.slug %}">View options</a></div>
                        </div>
                    </div>
                </div>
            {% endfor %}  
        </div>
    </div>
</section>
{% endblock main %}

product/templates/products/comment_confirm_delete.html
{% extends "base/base.html" %}
{% load humanize %}

{% block title %}comment{% endblock title %}

{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop</h1>
            <p class="lead fw-normal text-white-50 mb-0">Write Your Comment For This Product</p>
        </div>
    </div>
</header>
{% endblock header %}


{% block main %}
<br><br><br><br>
<div class="container my-5">
    <div class="card shadow">
        <div class="card-header bg-danger text-white">
            <h4 class="mb-0">Delete Comment</h4>
        </div>
        <div class="card-body">
            <p class="lead">Are You Sure You Want Delete Your Comment?</p>
            <blockquote class="blockquote mb-4">
                <p>"{{ object.comment }}"</p>
                <footer class="blockquote-footer">{{ object.author.username }}</footer>
            </blockquote>
            <form method="post">
                {% csrf_token %}
                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-danger">
                        <i class="bi bi-trash3 me-2"></i>Delete
                    </button>
                    <a href="{{ object.product.get_absolute_url }}" class="btn btn-secondary">
                        <i class="bi bi-arrow-left-circle me-2"></i>Cancel
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
<br><br><br><br>
{% endblock main %}

product/templates/products/detail.html
{% extends "base/base.html" %}
{% load humanize %}

{% block title %}{{product.name}}{% endblock title %}

{% block main %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                <div class="mb-4">
                    <img id="mainImage" class="img-fluid rounded" 
                         src="{% if product.tumbnail %}{{ product.tumbnail.url }}{% else %}https://dummyimage.com/600x700/dee2e6/6c757d.jpg{% endif %}" 
                         alt="{{product.name}}" style="max-height: 500px; width: 100%; object-fit: contain;">
                </div>
                
                {% if product.productimage_set.all %}
                <div class="thumbnail-gallery d-flex flex-wrap gap-2 mt-3">
                    <div class="thumbnail-item border p-1" style="cursor: pointer; width: 80px; height: 80px;">
                        <img src="{% if product.tumbnail %}{{ product.tumbnail.url }}{% else %}https://dummyimage.com/600x700/dee2e6/6c757d.jpg{% endif %}" 
                             class="w-100 h-100 object-fit-cover"
                             onclick="changeMainImage(this.src)" 
                             alt="{{product.name}} thumbnail">
                    </div>
                    
                    {% for image in product.productimage_set.all %}
                    <div class="thumbnail-item border p-1" style="cursor: pointer; width: 80px; height: 80px;">
                        <img src="{{ image.images.url }}" 
                             class="w-100 h-100 object-fit-cover"
                             onclick="changeMainImage(this.src)" 
                             alt="Product image {{ forloop.counter }}">
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>

            <div class="col-md-6">
                <div class="small mb-1">{{product.slug}}</div>
                <h1 class="display-5 fw-bolder">{{product.name}}</h1>
                <div class="fs-5 mb-5">
                    {% if product.is_sale %}
                    <span class="text-muted text-decoration-line-through">${{product.price|intcomma}}</span>
                    ${{product.sale_price}}
                    {% else %}
                    ${{product.price|intcomma}}
                    {% endif %}
                </div>
                <p class="lead">{{product.description}}</p>
                <p class="lead">{{product.info}}</p>
                
                <div class="mb-3">
                    <p class="lead">Color:</p>
                    <select class="form-select" id="cart-color">
                        {% for color in product.color.all %}
                            <option value="{{ color.id }}">{{ color.color }}</option>
                        {% endfor %}    
                    </select>
                </div>
                <p class="lead">Category: {{product.category}}</p>
                
                <div class="d-flex gap-3">
                    {% if product.quantity != 0 %}
                    <button class="btn btn-outline-dark flex-shrink-0" type="button" 
                            value="{{ product.id }}" id="add-cart">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                    </button>
                    <form method="POST" action="{% url 'product:favourite_product' product.slug %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger">
                          {% if request.user in product.favourites.all %}
                          💔 
                          {% else %}
                          ❤️
                          {% endif %}
                        </button>
                      </form>
                    {% else %}
                      <p class="lead" style="color: red;">Out Of Stock</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">New Arrivals</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in newarrivals %}
            <div class="col mb-5">
                <div class="card h-100">
                    {% if newarrival.is_sale %}
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    {% endif %}
                    <img class="card-img-top" src="{{ product.tumbnail.url }}" alt="{{product.name}}" />
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">{{product.name}}</h5>
                            {% if product.is_sale %}
                            <span class="text-muted text-decoration-line-through">${{product.price|intcomma}}</span>
                            ${{product.sale_price}}
                            {% else %}
                            ${{product.price|intcomma}}
                            {% endif %}
                            <br>
                            {{product.category}}
                        </div>
                    </div>
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product:product_detail' product.slug %}">View options</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <h2 class="fw-bolder mb-4">Comments({{comments.count}})</h2>
        <div class="row gx-4 gx-lg-5">
            {% for comment in comments %}
            <div class="col-12 mb-4">
                <div class="card p-3 shadow-sm">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <h5 class="text-primary mb-0">
                                <small class="text-muted">@{{comment.author.username}}</small>
                            </h5>
                            <small class="text-muted">{{comment.date|naturalday}}</small>
                        </div>
                        {% if user == comment.author %}
                        <div class="btn-group">
                            <a href="{% url 'product:comment_edit' comment.slug %}" 
                            class="btn btn-sm btn-outline-secondary">
                            <i class="bi bi-pencil"></i></a>
                            <a href="{% url 'product:comment_delete' comment.slug %}" 
                            class="btn btn-sm btn-outline-danger">
                            <i class="bi bi-trash"></i>
                            </a>
                        </div>
                        {% endif %}
                    </div>
                    <hr>
                    <p class="mb-0">{{comment.comment}}</p>
                </div>
            </div>
            {% empty %}
            <div class="alert alert-info">Not Comment Yet</div>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <div class="mt-5">
            <h4 class="mb-3">New Comment</h4>
            <form method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <textarea 
                        name="comment" 
                        class="form-control" 
                        placeholder=""
                        style="height: 100px"
                        required></textarea>
                    <label>Write Your Comment Here:</label>
                </div>
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-send me-2"></i>Submit
                </button>
            </form>
        </div>
        {% else %}
        <div class="alert alert-warning mt-4">
            <a href="{% url 'accounts:login' %}?next={{request.path}}" class="alert-link">You Should Login First</a>
        </div>
        {% endif %}
    </div>
</section>

<script>
    function changeMainImage(newSrc) {
        document.getElementById('mainImage').src = newSrc;
        
        const mainImg = document.getElementById('mainImage');
        mainImg.style.opacity = '0.5';
        setTimeout(() => {
            mainImg.style.opacity = '1';
        }, 200);
    }

    $(document).on('click', '#add-cart', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                product_id: $('#add-cart').val(),
                product_color: $('#cart-color').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(json) {
                $('#cart-quantity').text(json.quantity);
                alert('Product added to cart!');
            },
            error: function(xhr, errmsg, err) {
                console.log(xhr.status + ": " + xhr.responseText);
            }
        });
    });
    
</script>

<style>
    .tumbnail-item:hover {
        border-color: #0d6efd !important;
        transform: scale(1.05);
        transition: all 0.2s ease;
    }
    
    .object-fit-cover {
        object-fit: cover;
    }
    .card {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 0.5rem 1rem rgba(0,0,0,0.15);
    }

</style>
{% endblock main %}

product/templates/products/favouritelist.html
{% extends "base/base.html" %}
{% load humanize %}

{% block title %}My Favorites{% endblock %}

{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">My Favorites</h1>
            <p class="lead fw-normal text-white-50 mb-0">Your Wishlist Items</p>
        </div>
    </div>
</header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <center>
            <div class="col-12">
                {% if favourites %}
                <br>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in favourites %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            {% if product.is_sale %}
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            {% endif %}
                            <img class="card-img-top" src="{{ product.tumbnail.url }}" alt="{{product.name}}" />
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">{{product.name}}</h5>
                                    {% if product.is_sale %}
                                    <span class="text-muted text-decoration-line-through">${{product.price|intcomma}}</span>
                                    ${{product.sale_price|intcomma}}
                                    {% else %}
                                    ${{product.price|intcomma}}
                                    {% endif %}
                                    <br>
                                    {{product.category}}
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="{% url 'product:product_detail' product.slug %}">View Details</a>
                                </div>
                                <form method="POST" action="{% url 'product:favourite_product' product.slug %}" class="mt-2">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger w-100">
                                        {% if request.user in product.favourites.all %}
                                        Remove Favorite
                                        {% else %}
                                        Add Favorite
                                        {% endif %}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="card shadow-sm my-5">
                    <div class="card-body text-center py-5">
                        <i class="bi bi-heart text-danger" style="font-size: 3rem;"></i>
                        <h4 class="mt-3">Your Favorites List is Empty</h4>
                        <p class="text-muted">Click the heart icon on products to add items here</p>
                        <a href="{% url 'product:products' %}" class="btn btn-dark mt-3"><i class="bi bi-arrow-left me-1"></i>
                          Back to Shop
                      </a>
                  </div>
              </div>
              {% endif %}
          </div>
      </center>
  </div>
</div>

<style>
  .card {
      transition: transform 0.3s ease, box-shadow 0.3s ease;
  }
  .card:hover {
      transform: translateY(-5px);
      box-shadow: 0 0.5rem 1rem rgba(0,0,0,0.15);
  }
  .btn-outline-danger:hover {
      background-color: #dc3545;
      color: white;
  }
</style>
{% endblock %}

product/templates/products/search.html
{% extends "base/base.html" %}
{% load humanize %}

{% block title %}Search{% endblock title %}

{% block header %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Search</h1>
            <p class="lead fw-normal text-white-50 mb-0">Search Products Are Here!</p>
        </div>
    </div>
</header>
{% endblock header %}


{% block main %}
<br><br>
<br><br><br>
<div class="container">
    <div class="row">
        <center>
            <div class="=col-10">
                <div class="card">
                    <div class="card-header">
                    Search
                    </div>
                    <div class="card-body">
                    <form method="POST" action="{% url 'product:search' %}">
                        {% csrf_token %}
                        <input type="text" class="form-control" placeholder="search here" name="searched">
                        <br>
                        <button type="submit" class="col-md-12 btn btn-dark">Search</button>
                    </form>
                    </div>
                </div>
                <br><br><br>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% if searched %}
                    {% for product in searched %}
                        <div class="col mb-5">
                        <div class="card h-100">
                            {% if product.is_sale %}
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            {% endif %}
                            <img class="card-img-top" src="{{ product.tumbnail.url }}" alt="{{product.name}}" />
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">{{product.name}}</h5>
                                    {% if product.is_sale %}
                                    <span class="text-muted text-decoration-line-through">${{product.price|intcomma}}</span>
                                    ${{product.sale_price}}
                                    {% else %}
                                    ${{product.price|intcomma}}
                                    {% endif %}
                                    <br>
                                    {{product.category}}
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product:product_detail' product.slug %}">View options</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <div class="alert alert-danger mt-4 text-center">
                     "{{ request.POST.searched }} Not Found"
                    </div>
                {% endif %}
                </div>
            </div>
        </center>
    </div>
</div>
<br><br>
<br><br><br><br>
{% endblock main %}